/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(reader.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c8a0b16b200fd941416b99525f9cba08)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rfid/reader.h>
// pydoc.h is automatically generated in the build directory
#include <reader_pydoc.h>

void bind_reader(py::module& m)
{

    using reader = ::gr::rfid::reader;


    py::class_<reader, gr::block, gr::basic_block, std::shared_ptr<reader>>(
        m, "reader", D(reader))

        .def(py::init(&reader::make),
             py::arg("sample_rate"),
             py::arg("dac_rate"),
             D(reader, make))


        ;
}
